graph LR
    1["Test Selection"]
    2["One"]
    3["Continuous"]
    4["None"]
    5["One-sample T-test"]
    6["One"]
    7["Continuous"]
    8["Pearson correlation or regression"]
    9["Bootstrap correlation/regression, Spearman correlation, Kendall's tau"]
    10["Categorical"]
    11["Two"]
    12["Same"]
    13["Paired-samples T-test (Dependent T-test)"]
    14["Bootstrapped T-test or Wilcoxon signed-rank test"]
    15["Different"]
    16["Independent T-test or Pointbiserial correlation"]
    17["Bootstrapped T-test or Mann-Whitney test"]
    18["More than two"]
    19["Same"]
    20["One-way repeated measures ANOVA"]
    21["Bootstrapped ANOVA or Friedman's ANOVA"]
    22["Different"]
    23["One-way independent ANOVA"]
    24["Robust ANOVA or Kruskal-Wallis test"]
    25["Two or more"]
    26["Continuous"]
    27["Multiple regression"]
    28["Bootstrapped multiple regression"]
    29["Categorical"]
    30["Same"]
    31["Factorial repeated measures ANOVA"]
    32["Robust factorial repeated measures ANOVA"]
    33["Different"]
    34["Independent factorial ANOVA/multiple regression"]
    35["Robust independent factorial ANOVA/multiple regression"]
    36["Both"]
    37["Factorial mixed ANOVA"]
    38["Robust factorial mixed ANOVA"]
    39["Both"]
    40["Multiple regression/ANCOVA"]
    41["Robust ANCOVA/bootstrapped regression"]
    42["Categorical"]
    43["One"]
    44["Continuous"]
    45["Logistic regression or biserial/point biserialcorrelation"]
    46["Categorical"]
    47["Different"]
    48["Pearson chi-square or likelihood ratio"]
    49["Two or more"]
    50["Continuous"]
    51["Logistic regression"]
    52["Categorical"]
    53["Different"]
    54["Loglinear analysis"]
    55["Both"]
    56["Different"]
    57["Logistic regression"]
    58["Two or more"]
    59["Continuous"]
    60["One"]
    61["Categorical"]
    62["MANOVA"]
    63["Two or more"]
    64["Categorical"]
    65["Factorial MANOVA"]
    66["Both"]
    67["MANCOVA"]
    NA --> 1
    1 --> 2
    2 --> 3
    3 --> 4
    4 --> 5
    3 --> 6
    6 --> 7
    7 --> 8
    8 --> 9
    6 --> 10
    10 --> 11
    11 --> 12
    12 --> 13
    13 --> 14
    11 --> 15
    15 --> 16
    16 --> 17
    10 --> 18
    18 --> 19
    19 --> 20
    20 --> 21
    18 --> 22
    22 --> 23
    23 --> 24
    3 --> 25
    25 --> 26
    26 --> 27
    27 --> 28
    25 --> 29
    29 --> 30
    30 --> 31
    31 --> 32
    29 --> 33
    33 --> 34
    34 --> 35
    29 --> 36
    36 --> 37
    37 --> 38
    25 --> 39
    39 --> 40
    40 --> 41
    2 --> 42
    42 --> 43
    43 --> 44
    44 --> 45
    43 --> 46
    46 --> 47
    47 --> 48
    42 --> 49
    49 --> 50
    50 --> 51
    49 --> 52
    52 --> 53
    53 --> 54
    49 --> 55
    55 --> 56
    56 --> 57
    1 --> 58
    58 --> 59
    59 --> 60
    60 --> 61
    61 --> 62
    59 --> 63
    63 --> 64
    64 --> 65
    63 --> 66
    66 --> 67
