flowchart LR

A -->|AA| A -->|AA| AA -->|AAB| AA -->|AAB| AAB -->|AABA| AAB -->|AABA| AABAAAAM --> AABAAAAME
A -->|AA| AA -->|AAB| AAB -->|AABB| AABB -->|AABBD| AABBDAAR --> AABBDAARB
A -->|AA| AA -->|AAB| AAB -->|AABB| AABB -->|AABBC| AABBC -->|AABBCC| AABBCC -->|AABBCCD| AABBCCDP --> AABBCCDPG
A -->|AA| AA -->|AAB| AAB -->|AABB| AABB -->|AABBC| AABBC -->|AABBCC| AABBCC -->|AABBCCC| AABBCCCE --> AABBCCCEF
A -->|AA| AA -->|AAB| AAB -->|AABB| AABB -->|AABBC| AABBC -->|AABBCB| AABBCB -->|AABBCBD| AABBCBDO --> AABBCBDOC
A -->|AA| AA -->|AAB| AAB -->|AABB| AABB -->|AABBC| AABBC -->|AABBCB| AABBCB -->|AABBCBC| AABBCBCN --> AABBCBCNI
A -->|AA| AA -->|AAB| AAB -->|AABC| AABC -->|AABCD| AABCDAAK --> AABCDAAKD
A -->|AA| AA -->|AAB| AAB -->|AABC| AABC -->|AABCC| AABCCADC --> AABCCADCK
A -->|AA| AA -->|AAB| AAB -->|AABC| AABC -->|AABCC| AABCCACD --> AABCCACDL
A -->|AA| AA -->|AAB| AAB -->|AABC| AABC -->|AABCC| AABCCABB --> AABCCABBJ
A -->|AA| AA -->|AAB| AAB -->|AABC| AABC -->|AABCB| AABCBAAL --> AABCBAALH
A -->|AA| AA -->|AAA| AAA -->|AAAB| AAAB -->|AAABD| AAABDAAG
A -->|AA| AA -->|AAA| AAA -->|AAAB| AAAB -->|AAABC| AAABCACQ
A -->|AA| AA -->|AAA| AAA -->|AAAC| AAAC -->|AAACD| AAACDAAF
A -->|AA| AA -->|AAA| AAA -->|AAAC| AAAC -->|AAACC| AAACCACH
A -->|AA| AA -->|AAA| AAA -->|AAAC| AAAC -->|AAACB| AAACBACF
A -->|AB| AB -->|ABB| ABB -->|ABBB| ABBB -->|ABBBC| ABBBCACJ
A -->|AB| AB -->|ABB| ABB -->|ABBC| ABBC -->|ABBCC| ABBCCACA
A -->|AB| AB -->|ABB| ABB -->|ABBC| ABBC -->|ABBCB| ABBCBAAI
