flowchart LR
  A{"#DV"} -->|"AA"| AA
  AA{"DV<br>type"} -->|"AAB"| AAB
  AAB{"#IV"} -->|"AABA"| AABA
  AAB{"#IV"} -->|"AABB"| AABB
  AABA{"IV<br>type"} -->|"AABAAAAM"| AABAAAAM
  AABB{"IV<br>type"} -->|"AABBD"| AABBD
  AABBD{"#Cat"} -->|"AABBDAAR"| AABBDAAR
