flowchart LR
1_DV_number{"DV number"}
2_DV_type{"DV type"}
3_IV_number{"IV number"}
4_IV_type{"IV type"}
5_IV_categories{"IV categories"}
6_Category_samples{"Category samples"}
7_Parametric_Test{"Parametric Test"}
8_Non-parametric_test{"Non-parametric test"}

