flowchart LR
  DVn{#DV} -->|One| DVnOne{DV<br>type}
  DVn{#DV} -->|Two or more| DVnTwoormore{DV<br>type}
  DVnOne -->|Continuous| DVnOneContinuous{#IV}
  DVnOne -->|Categorical| DVnOneCategorical{#IV}
  DVnTwoormore -->|Continuous| DVnTwoormoreContinuous{#IV}
  DVnOneContinuous -->|None| PTOne-sampleT-test["One-sample T-test"]
  DVnOneContinuous -->|One| DVnOneContinuousOne{IV<br>type}
  DVnOneContinuous -->|Two or more| DVnOneContinuousTwoormore{IV<br>type}
  DVnOneCategorical -->|One| DVnOneCategoricalOne{IV<br>type}
  DVnOneCategorical -->|Two or more| DVnOneCategoricalTwoormore{IV<br>type}
  DVnTwoormoreContinuous -->|One| DVnTwoormoreContinuousOne{IV<br>type}
  DVnTwoormoreContinuous -->|Two or more| DVnTwoormoreContinuousTwoormore{IV<br>type}

  DVnOneContinuousOne -->|Continuous| DVnOneContinuousOneContinuous{#Cat}
  DVnOneContinuousOne -->|Categorical| DVnOneContinuousOneCategorical{#Cat}
  DVnOneContinuousTwoormore -->|Continuous| DVnOneContinuousTwoormoreContinuous{#Cat}
  DVnOneContinuousTwoormore -->|Categorical| DVnOneContinuousTwoormoreCategorical{#Cat}
  DVnOneContinuousTwoormore -->|Both| DVnOneContinuousTwoormoreBoth{#Cat}
  DVnOneCategoricalOne -->|Continuous| DVnOneCategoricalOneContinuous{#Cat}
  DVnOneCategoricalOne -->|Categorical| DVnOneCategoricalOneCategorical{#Cat}
  DVnOneCategoricalTwoormore -->|Continuous| DVnOneCategoricalTwoormoreContinuous{#Cat}
  DVnOneCategoricalTwoormore -->|Categorical| DVnOneCategoricalTwoormoreCategorical{#Cat}
  DVnOneCategoricalTwoormore -->|Both| DVnOneCategoricalTwoormoreBoth{#Cat}
  DVnTwoormoreContinuousOne -->|Categorical| DVnTwoormoreContinuousOneCategorical{#Cat}
  DVnTwoormoreContinuousTwoormore -->|Categorical| DVnTwoormoreContinuousTwoormoreCategorical{#Cat}
  DVnTwoormoreContinuousTwoormore -->|Both| DVnTwoormoreContinuousTwoormoreBoth{#Cat}

  DVnOneContinuousOneContinuous -->| | DVnOneContinuousOneContinuousNA{Samp}
  DVnOneContinuousOneCategorical -->|Two| DVnOneContinuousOneCategoricalTwo{Samp}
  DVnOneContinuousOneCategorical -->|More than two| DVnOneContinuousOneCategoricalMorethantwo{Samp}
  DVnOneContinuousTwoormoreContinuous -->| | DVnOneContinuousTwoormoreContinuousNA{Samp}
  DVnOneContinuousTwoormoreCategorical -->| | DVnOneContinuousTwoormoreCategoricalNA{Samp}
  DVnOneContinuousTwoormoreBoth -->| | DVnOneContinuousTwoormoreBothNA{Samp}
  DVnOneCategoricalOneContinuous -->| | DVnOneCategoricalOneContinuousNA{Samp}
  DVnOneCategoricalOneCategorical -->| | DVnOneCategoricalOneCategoricalNA{Samp}
  DVnOneCategoricalTwoormoreContinuous -->| | DVnOneCategoricalTwoormoreContinuousNA{Samp}
  DVnOneCategoricalTwoormoreCategorical -->| | DVnOneCategoricalTwoormoreCategoricalNA{Samp}
  DVnOneCategoricalTwoormoreBoth -->| | DVnOneCategoricalTwoormoreBothNA{Samp}
  DVnTwoormoreContinuousOneCategorical -->| | DVnTwoormoreContinuousOneCategoricalNA{Samp}
  DVnTwoormoreContinuousTwoormoreCategorical -->| | DVnTwoormoreContinuousTwoormoreCategoricalNA{Samp}
  DVnTwoormoreContinuousTwoormoreBoth -->| | DVnTwoormoreContinuousTwoormoreBothNA{Samp}

  DVnOneContinuousOneContinuousNA -->| | PTPearsoncorrelationorregression["Pearson correlation or regression"]
  DVnOneContinuousOneCategoricalTwo -->|Repeated| PTPaired-samplesT-testDependentT-test["Paired-samples T-test (Dependent T-test)"]
  DVnOneContinuousOneCategoricalTwo -->|Independent| PTIndependentT-testorPointbiserialcorrelation["Independent T-test or Pointbiserial correlation"]
  DVnOneContinuousOneCategoricalMorethantwo -->|Repeated| PTOne-wayrepeatedmeasuresANOVA["One-way repeated measures ANOVA"]
  DVnOneContinuousOneCategoricalMorethantwo -->|Independent| PTOne-wayindependentANOVA["One-way independent ANOVA"]
  DVnOneContinuousTwoormoreContinuousNA -->| | PTMultipleregression["Multiple regression"]
  DVnOneContinuousTwoormoreCategoricalNA -->|Repeated| PTFactorialrepeatedmeasuresANOVA["Factorial repeated measures ANOVA"]
  DVnOneContinuousTwoormoreCategoricalNA -->|Independent| PTIndependentfactorialANOVA/multipleregression["Independent factorial ANOVA/multiple regression"]
  DVnOneContinuousTwoormoreCategoricalNA -->|Both| PTFactorialmixedANOVA["Factorial mixed ANOVA"]
  DVnOneContinuousTwoormoreBothNA -->| | PTMultipleregression/ANCOVA["Multiple regression/ANCOVA"]
  DVnOneCategoricalOneContinuousNA -->| | PTLogisticregressionorbiserial/pointbiserialcorrelation["Logistic regression or biserial/point biserialcorrelation"]
  DVnOneCategoricalOneCategoricalNA -->|Independent| PTPearsonchi-squareorlikelihoodratio["Pearson chi-square or likelihood ratio"]
  DVnOneCategoricalTwoormoreContinuousNA -->| | PTLogisticregression["Logistic regression"]
  DVnOneCategoricalTwoormoreCategoricalNA -->|Independent| PTLoglinearanalysis["Loglinear analysis"]
  DVnOneCategoricalTwoormoreBothNA -->|Independent| PTLogisticregression["Logistic regression"]
  DVnTwoormoreContinuousOneCategoricalNA -->|Independent| PTMANOVA["MANOVA"]
  DVnTwoormoreContinuousTwoormoreCategoricalNA -->|Independent| PTFactorialMANOVA["Factorial MANOVA"]
  DVnTwoormoreContinuousTwoormoreBothNA -->| | PTMANCOVA["MANCOVA"]
  PTOne-sampleT-test --> NPTBootstrappedT-test["Bootstrapped T-test"]
  PTPearsoncorrelationorregression --> NPTBootstrapcorrelation/regression,Spearmancorrelation,Kendall'stau["Bootstrap correlation/regression, Spearman correlation, Kendall's tau"]
  PTPaired-samplesT-testDependentT-test --> NPTBootstrappedT-testorWilcoxonsigned-ranktest["Bootstrapped T-test or Wilcoxon signed-rank test"]
  PTIndependentT-testorPointbiserialcorrelation --> NPTBootstrappedT-testorMann-Whitneytest["Bootstrapped T-test or Mann-Whitney test"]
  PTOne-wayrepeatedmeasuresANOVA --> NPTBootstrappedANOVAorFriedman'sANOVA["Bootstrapped ANOVA or Friedman's ANOVA"]
  PTOne-wayindependentANOVA --> NPTRobustANOVAorKruskal-Wallistest["Robust ANOVA or Kruskal-Wallis test"]
  PTMultipleregression --> NPTBootstrappedmultipleregression["Bootstrapped multiple regression"]
  PTFactorialrepeatedmeasuresANOVA --> NPTRobustfactorialrepeatedmeasuresANOVA["Robust factorial repeated measures ANOVA"]
  PTIndependentfactorialANOVA/multipleregression --> NPTRobustindependentfactorialANOVA/multipleregression["Robust independent factorial ANOVA/multiple regression"]
  PTFactorialmixedANOVA --> NPTRobustfactorialmixedANOVA["Robust factorial mixed ANOVA"]
  PTMultipleregression/ANCOVA --> NPTRobustANCOVA/bootstrappedregression["Robust ANCOVA/bootstrapped regression"]

subgraph Parametric Tests
PTOne-sampleT-test
PTPearsoncorrelationorregression
PTPaired-samplesT-testDependentT-test
PTIndependentT-testorPointbiserialcorrelation
PTOne-wayrepeatedmeasuresANOVA
PTOne-wayindependentANOVA
PTMultipleregression
PTFactorialrepeatedmeasuresANOVA
PTIndependentfactorialANOVA/multipleregression
PTFactorialmixedANOVA
PTMultipleregression/ANCOVA
PTLogisticregressionorbiserial/pointbiserialcorrelation
PTPearsonchi-squareorlikelihoodratio
PTLogisticregression
PTLoglinearanalysis
PTLogisticregression
PTMANOVA
PTFactorialMANOVA
PTMANCOVA
end
subgraph Non Parametric Tests
NPTBootstrappedT-test
NPTBootstrapcorrelation/regression,Spearmancorrelation,Kendall'stau
NPTBootstrappedT-testorWilcoxonsigned-ranktest
NPTBootstrappedT-testorMann-Whitneytest
NPTBootstrappedANOVAorFriedman'sANOVA
NPTRobustANOVAorKruskal-Wallistest
NPTBootstrappedmultipleregression
NPTRobustfactorialrepeatedmeasuresANOVA
NPTRobustindependentfactorialANOVA/multipleregression
NPTRobustfactorialmixedANOVA
NPTRobustANCOVA/bootstrappedregression
end
