flowchart LR
  A{"#DV"} -->|"AA"| AA
  A{"#DV"} -->|"AB"| AB
  AA{"DV<br>type"} -->|"AAB"| AAB
  AA{"DV<br>type"} -->|"AAA"| AAA
  AB{"DV<br>type"} -->|"ABB"| ABB
  AAB{"#IV"} -->|"AABA"| AABA
  AAB{"#IV"} -->|"AABB"| AABB
  AAB{"#IV"} -->|"AABC"| AABC
  AAA{"#IV"} -->|"AAAB"| AAAB
  AAA{"#IV"} -->|"AAAC"| AAAC
  ABB{"#IV"} -->|"ABBB"| ABBB
  ABB{"#IV"} -->|"ABBC"| ABBC
  AABA{"IV<br>type"} -->|"AABAAAAM"| AABAAAAM
  AABB{"IV<br>type"} -->|"AABBD"| AABBD
  AABB{"IV<br>type"} -->|"AABBC"| AABBC
  AABC{"IV<br>type"} -->|"AABCD"| AABCD
  AABC{"IV<br>type"} -->|"AABCC"| AABCC
  AABC{"IV<br>type"} -->|"AABCB"| AABCB
  AAAB{"IV<br>type"} -->|"AAABD"| AAABD
  AAAB{"IV<br>type"} -->|"AAABC"| AAABC
  AAAC{"IV<br>type"} -->|"AAACD"| AAACD
  AAAC{"IV<br>type"} -->|"AAACC"| AAACC
  AAAC{"IV<br>type"} -->|"AAACB"| AAACB
  ABBB{"IV<br>type"} -->|"ABBBC"| ABBBC
  ABBC{"IV<br>type"} -->|"ABBCC"| ABBCC
  ABBC{"IV<br>type"} -->|"ABBCB"| ABBCB
  AABBD{"#Cat"} -->|"AABBDAAR"| AABBDAAR
  AABBC{"#Cat"} -->|"AABBCC"| AABBCC
  AABBC{"#Cat"} -->|"AABBCB"| AABBCB
  AABCD{"#Cat"} -->|"AABCDAAK"| AABCDAAK
  AABCC{"#Cat"} -->|"AABCCAD"| AABCCAD
  AABCC{"#Cat"} -->|"AABCCAC"| AABCCAC
  AABCC{"#Cat"} -->|"AABCCAB"| AABCCAB
  AABCB{"#Cat"} -->|"AABCBAAL"| AABCBAAL
  AAABD{"#Cat"} -->|"AAABDAAG"| AAABDAAG
  AAABC{"#Cat"} -->|"AAABCAC"| AAABCAC
  AAACD{"#Cat"} -->|"AAACDAAF"| AAACDAAF
  AAACC{"#Cat"} -->|"AAACCAC"| AAACCAC
  AAACB{"#Cat"} -->|"AAACBAC"| AAACBAC
  ABBBC{"#Cat"} -->|"ABBBCAC"| ABBBCAC
  ABBCC{"#Cat"} -->|"ABBCCAC"| ABBCCAC
  ABBCB{"#Cat"} -->|"ABBCBAAI"| ABBCBAAI
  AABBCC{"Samp"} -->|"AABBCCD"| AABBCCD
  AABBCC{"Samp"} -->|"AABBCCC"| AABBCCC
  AABBCB{"Samp"} -->|"AABBCBD"| AABBCBD
  AABBCB{"Samp"} -->|"AABBCBC"| AABBCBC
  AABBCCD{"PT"} -->|"AABBCCDP"| AABBCCDP
  AABBCCC{"PT"} -->|"AABBCCCE"| AABBCCCE
  AABBCBD{"PT"} -->|"AABBCBDO"| AABBCBDO
  AABBCBC{"PT"} -->|"AABBCBCN"| AABBCBCN
  AABCCAD{"PT"} -->|"AABCCADC"| AABCCADC
  AABCCAC{"PT"} -->|"AABCCACD"| AABCCACD
  AABCCAB{"PT"} -->|"AABCCABB"| AABCCABB
  AAABCAC{"PT"} -->|"AAABCACQ"| AAABCACQ
  AAACCAC{"PT"} -->|"AAACCACH"| AAACCACH
  AAACBAC{"PT"} -->|"AAACBACF"| AAACBACF
  ABBBCAC{"PT"} -->|"ABBBCACJ"| ABBBCACJ
  ABBCCAC{"PT"} -->|"ABBCCACA"| ABBCCACA
