---
config:
  layout: dagre
  look: classic
  theme: default
---

graph LR
    
    classDef test height:100%,fill:#f9f,stroke:#333,stroke-width:1px,font-size:150%;



    2["One"]
    3["Continuous"]
    4["None"]
    5["One-sample T-test"]
    6["One"]
    7["Continuous"]
    8["Pearson correlation or regression"]
    9["Bootstrap correlation/regression, Spearman correlation, Kendall's tau"]
    10["Categorical"]
    11["Two"]
    12["Same"]
    13["Paired-samples T-test (Dependent T-test)"]
    14["Bootstrapped T-test or Wilcoxon signed-rank test"]
    15["Different"]
    16["Independent T-test or Pointbiserial correlation"]
    17["Bootstrapped T-test or Mann-Whitney test"]
    18["More than two"]
    19["Same"]
    20["One-way repeated measures ANOVA"]
    21["Bootstrapped ANOVA or Friedman's ANOVA"]
    22["Different"]
    23["One-way independent ANOVA"]
    24["Robust ANOVA or Kruskal-Wallis test"]
    25["Two or more"]
    26["Continuous"]
    27["Multiple regression"]
    28["Bootstrapped multiple regression"]
    29["Categorical"]
    30["Same"]
    31["Factorial repeated measures ANOVA"]
    32["Robust factorial repeated measures ANOVA"]
    33["Different"]
    34["Independent factorial ANOVA/multiple regression"]
    35["Robust independent factorial ANOVA/multiple regression"]
    36["Both"]
    37["Factorial mixed ANOVA"]
    38["Robust factorial mixed ANOVA"]
    39["Both"]
    40["Multiple regression/ANCOVA"]
    41["Robust ANCOVA/bootstrapped regression"]
    42["Categorical"]
    43["One"]
    44["Continuous"]
    45["Logistic regression or biserial/point biserialcorrelation"]
    46["Categorical"]
    47["Different"]
    48["Pearson chi-square or likelihood ratio"]
    49["Two or more"]
    50["Continuous"]
    51["Logistic regression"]
    52["Categorical"]
    53["Different"]
    54["Loglinear analysis"]
    55["Both"]
    56["Different"]
    57["Logistic regression"]
    58["Two or more"]
    59["Continuous"]
    60["One"]
    61["Categorical"]
    62["MANOVA"]
    63["Two or more"]
    64["Categorical"]
    65["Factorial MANOVA"]
    66["Both"]
    67["MANCOVA"]

    ndv["Number of DVs"]:::test

    subgraph ndv
    2
    58
    end

todv["Type of DV"]:::test

    subgraph todv
    2 --> 3
    2 --> 42
    58 --> 59
    end
    subgraph Number of IVs
    3 --> 4
    3 --> 6
    3 --> 25
    42 --> 49
    42 --> 43
    59 --> 60
    59 --> 63
    end
    subgraph Type of IVs
    6 --> 7
    6 --> 10
    25 --> 26
    25 --> 29
    25 --> 39
    49 --> 50
    49 --> 52
    49 --> 55    
    43 --> 44
    43 --> 46
    60 --> 61
    63 --> 64
    63 --> 66
    end


    ng["Number of Groups/Levels"]:::test
    
    subgraph ng
    10 --> 11
    10 --> 18
    end
    

    indrep["Independent groups or repeated measures"]:::test
  
    subgraph indrep
    11 --> 12
    11 --> 15
    18 --> 19
    18 --> 22
    29 --> 30
    29 --> 33
    29 --> 36
    52 --> 53
    44 --> 45
    46 --> 47
    55 --> 56
    end

    subgraph Parametric tests
    7 --> 8
    4 --> 5
    12 --> 13
    15 --> 16
    19 --> 20
    22 --> 23
    26 --> 27
    30 --> 31
    33 --> 34
    36 --> 37
    39 --> 40

    47 --> 48
    50 --> 51
    53 --> 54
    56 --> 57
    61 --> 62
    64 --> 65
    66 --> 67
    end

    subgraph Non-parametric tests   
    8 --> 9
    13 --> 14
    16 --> 17
    20 --> 21
    23 --> 24
    27 --> 28
    31 --> 32
    34 --> 35
    37 --> 38
    40 --> 41
    end
    
   

    


    

    
    

